/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.telas;

import control.PacienteC;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JInternalFrame;
import javax.swing.ListSelectionModel;
import util.Yagami;

/**
 *
 * @author Juan
 */
public class ViewPaciente extends javax.swing.JInternalFrame {
    Timer timer = new Timer();
    /**
     * Creates new form Pacientes
     */
    
    public ViewPaciente() {
        initComponents();
        setLocation(100, 100);
        PacienteC.CONTROL.listTable(tablePaciente);
        
        float[] columnWidthPercentage = {10.0f, 60.0f, 15.0f, 15.0f};
        Yagami.resizeColumns(tablePaciente, columnWidthPercentage);
        
        tablePaciente.setRowSelectionAllowed(true);
        tablePaciente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        // LOOP
        timer.schedule( new TimerTask() {
            @Override
            public void run() {
                PacienteC.CONTROL.listTable(tablePaciente);
            }
         }, 0, 5000);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablePaciente = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnDetalhes = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Pacientes");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconXP.png"))); // NOI18N
        setName(""); // NOI18N
        setVisible(true);

        tablePaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Data Nascimento", "Sexo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablePacienteMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablePacienteMouseReleased(evt);
            }
        });
        tablePaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablePacienteKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tablePaciente);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Listagem de Pacientes");

        btnCadastrar.setText("Cadastrar Paciente");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnDetalhes.setText("Ver detalhes");
        btnDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalhesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDetalhes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCadastrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnCadastrar)
                    .addComponent(btnDetalhes))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablePacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePacienteMousePressed
        // TODO add your handling code here:
        //pushProduto();
    }//GEN-LAST:event_tablePacienteMousePressed

    private void tablePacienteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePacienteMouseReleased
        // TODO add your handling code here:
        //pushProduto();
    }//GEN-LAST:event_tablePacienteMouseReleased

    private void tablePacienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablePacienteKeyReleased
        // TODO add your handling code here:
        //pushProduto();
        
    }//GEN-LAST:event_tablePacienteKeyReleased

    private void btnDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalhesActionPerformed
        // TODO add your handling code here:
        JInternalFrame base = new Base();
        
        Yagami.exibirTela(base, getParent(), false);
    }//GEN-LAST:event_btnDetalhesActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        JInternalFrame cadPac = new CadPaciente();
        
        Yagami.exibirTela(cadPac, getParent(), true);
    }//GEN-LAST:event_btnCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnDetalhes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePaciente;
    // End of variables declaration//GEN-END:variables
}
